name: Build Geode Mod (Docker)

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

env:
  MOD_ID: the_bearodactyl.gay-wave-trail

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            target: windows
            artifact-name: geode-build-win

          - name: macOS
            target: macos
            artifact-name: geode-build-mac

          - name: iOS
            target: ios
            artifact-name: geode-build-ios

          - name: Android32
            target: android32
            artifact-name: geode-build-android32

          - name: Android64
            target: android64
            artifact-name: geode-build-android64

    name: ${{ matrix.config.name }}
    runs-on: codeberg-medium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update -q
          sudo apt-get install -qy podman

      - name: Build ${{ matrix.config.name }}
        run: |
          podman build \
            --target export-${{ matrix.config.target }} \
            --build-arg MOD_ID=${{ env.MOD_ID }} \
            --tag geode-export \
            .
          mkdir -p ./out
          cid=$(podman create geode-export)
          podman cp "$cid":/ ./out/
          podman rm "$cid"

      - name: Upload ${{ matrix.config.name }} artifact
        uses: action/upload-artifact@v4
        with:
          name: ${{ matrix.config.artifact-name }}
          path: ./out

  package:
    name: Package builds
    runs-on: codeberg-medium
    needs: ["build"]

    steps:
      - uses: https://github.com/geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
